// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkcpuwnmkublhcgcpnhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrY3B1d25ta3VibGhjZ2NwbmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MjczMjgsImV4cCI6MjA1MDUwMzMyOH0.ZlVBUR_gMri6pZLfJSgQKDMI_7xN9FR9HC0-6L5TqW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);